MyeShop/MyeShop.WebUI/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyeShop.Core.Contracts;

namespace MyeShop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IBasketService basketService;

        public BasketController(IBasketService BasketService)
        {
            this.basketService = BasketService;
        }
        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string Id)
        {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);

            return PartialView(basketSummary);
        }
    }
}

MyeShop/MyeShop.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyeShop.Core.Contracts;
using MyeShop.Core.Models;
using MyeShop.Core.ViewModels;

namespace MyeShop.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IRepository<Product> _context;
        public IRepository<ProductCategory> productCategories;

        public HomeController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext)
        {
            _context = productContext;
            productCategories = productCategoryContext;
        }

        public ActionResult Index(string Category = null)
        {

            List<Product> products;
            List<ProductCategory> categories = productCategories.Collection().ToList();

            if (Category == null)
            {
                products = _context.Collection().ToList();
            }
            else
            {
                products = _context.Collection().Where(p => p.Category == Category).ToList();
            }
            ProductListViewModel viewModel = new ProductListViewModel();

            viewModel.Products = products;
            viewModel.ProductCategories = categories;

            return View(viewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Details(string id)
        {
            Product product = _context.Find(id);
            if (product == null)
                return HttpNotFound();
            return View(product);
        }
    }
}

MyeShop/MyeShop.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyeShop/MyeShop.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyeShop/MyeShop.WebUI/Views/Home/Details.cshtml
@model MyeShop.Core.Models.Product

@{
    ViewBag.Title = Model.Name + "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<div>
    
    <div class="col-md-4">
        <img class="img-responsive" src="~/Content/ProductImages/@Model.Image"/>
    </div>
    
    <div class="col-md-8">
        <dl class="dl-horizontal">
            
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                $ @Html.DisplayFor(model => model.Price)
            </dd>
            
            <dt></dt>
            <dd>
                <a href="@Url.Action("AddToBasket", "Basket", new {Id = Model.Id})" class="btn btn-success">Add to Cart</a>
            </dd>
            <dt></dt>
            <dd>
                @Html.ActionLink("Back to List", "Index")
            </dd>

        </dl>
    </div>
</div>

<div class="col-md-12 clearfix" />

MyeShop/MyeShop.WebUI/Views/Home/Index.cshtml
@model MyeShop.Core.ViewModels.ProductListViewModel

@{
    ViewBag.Title = "Home Page";
}

<h2>Products</h2>

<div class="col-md-2">
    <h4>Filter by Category</h4>
    <div class="list-group">
        @Html.ActionLink("All", "Index", null, new { @class = Request["Category"] == null ? "list-group-item active" : "list-group-item"})
        @foreach (var cat in Model.ProductCategories)
        {
            @Html.ActionLink(cat.Category, "Index", new {Category = cat.Category}, new { @class = Request["Category"] == cat.Category ? "list-group-item active" : "list-group-item"})
        }
    </div>
</div>

<div class="col-md-10">
    @foreach (var item in Model.Products)
    {
        <div class="col-md-4" style="height: 400px; padding: 10px; margin: 10px; border: solid thin whitesmoke">
            <div class="col-md-12">
                <img src="~/Content/ProductImages/@item.Image" class="img" style="height: 160px" />
            </div>
            <div class="col-md-12">
                <strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong>
            </div>
            <div class="col-md-12">
                <span>@item.Description</span>
            </div>
            <div class="col-md-12">
                <span>$ @item.Price</span>
            </div>
            <div class="col-md-12">
                <a href="@Url.Action("AddToBasket", "Basket", new {Id = item.Id})" class="btn btn-success">Add to Cart</a>
            </div>
        </div>
    }
</div>


<div class="col-md-12 clearfix" />